### ISSUE TITLE
waydroid Not starting

### ISSUE THREAD

**Issue by NewthanGuy** [pagkly/magiskonwaydroid#3]
hi i fixed the service ploblem but now waydroid gets stuck at starting the session 

Used EndeavourOS

Screenshots soon

**Comment by pagkly** [comment]
Hi did you manage to get the screenshot? And what kernel did you use? I recommend linux-zen kernel.

Did you try waydroid 10 (default image) as well and show same error? If waydroid 10 also gave the same error then there might be some misconfiguration in your OS setup. For instance, Waydroid 11 use different gbinder config that you can (and must) change manually.

If the error is not related to the workflow build, its might be best to communicate with Endeavour forum or Waydroid Telegram. Otherwise, I might close this issue unless there are other users having similar issue in the next few weeks.

**Comment by NewthanGuy** [comment]
I did use Linux zen and i used the gbinder for Android 11 also i forgot to get the screenshot

**Comment by pagkly** [comment]
@NewthanGuy I just got my archlinux machine up and running again and surprisingly waydroid not launching at all with latest linux-zen/linux-mainline-anbox.
I tried changing the kernel to latest `linux-xanmod-anbox` with `psi=1 `on the kernel line and it works just like before. I noticed latest linux-zen didnt appear to have `ashmem` modules compiled.
I will update the install guide to use xanmod kernel instead.

**Comment by pagkly** [comment]
@NewthanGuy I just got my archlinux machine up and running again and surprisingly waydroid not launching at all.
I tried changing the kernel to latest `linux-xanmod-anbox` with `psi=1 `on the kernel line and it works just like before. I noticed latest linux-zen didnt appear to have `ashmem` modules compiled.
I will update the install guide to use xanmod kernel instead.

**Comment by NewthanGuy** [comment]
But how will I fix my existing install

**Comment by pagkly** [comment]
@NewthanGuy I have no idea, since I did not know what kind of error you encountered. There are many issues to troubleshoot to get Waydroid running. I need log ( such as output of `waydroid log` )/screenshot or else I can't help you much.
This is the latest I could get working:
![image](https://user-images.githubusercontent.com/28628331/171383357-95adab4d-de84-4358-8eaa-bdfe83d12bbc.png)

**Comment by NewthanGuy** [comment]
Ok i will btw i will with the original source of the issue aka Linux zen

**Comment by NewthanGuy** [comment]
okay! heres the screenshot
![Screenshot_20220602_120528](https://user-images.githubusercontent.com/51269213/171660996-f83332df-6077-4c20-b7bb-bd5672c8727c.png)

**Comment by NewthanGuy** [comment]
and this is the complete log
[waydroid.log](https://github.com/pagkly/MagiskOnWaydroid/files/8825152/waydroid.log)

**Comment by NewthanGuy** [comment]
i highly recommend to translate the portuguese parts of the ports to english as i am portugeuse
